### ISSUE TITLE
Error in installing 

### ISSUE THREAD

**Issue by karthikhooduku** [Armor-Payments/armor-payments-php#1]
hey,

when in run composer install

php composer.phar install

I get this following Error. Can you help me out

Generating autoload files

> php artisan clear-compiled
> PHP Warning:  require(/vendor/armorpayments/armorpayments-php/lib/ArmorPayments.php): failed to open stream: No such file or directory in vendor/composer/autoload_real.php on line 54
> PHP Fatal error:  require(): Failed opening required 'vendor/armorpayments/armorpayments-php/lib/ArmorPayments.php' (include_path='.:/usr/share/php:/usr/share/pear') in vendor/composer/autoload_real.php on line 54
> Script php artisan clear-compiled handling the post-install-cmd event returned with an error

  [RuntimeException]  
  Error Output: PHP Warning:  require(vendor/armorpayments/armorpayments-php/lib/ArmorPayments.php): failed to op  
  en stream: No such file or directory invendor/composer/autoload_real.php on line 54  
  PHP Fatal error:  require(): Failed opening required 'vendor/armorpayments/armorpayments-php/lib/ArmorPayments.  
  php' (include_path='.:/usr/share/php:/usr/share/pear') in vendor/composer/autoload_real.php on line 54

**Comment by mrmarkfrench** [comment]
So it looks like he problem is with this:
 `require(/vendor/armorpayments/armorpayments-php/lib/ArmorPayments.php)`

That's trying to load an absolute path, but using a path that appears to be intended to be relative to the root of your project. If you set that path, you should change it by removing the leading slash, but if that path is being generated by Composer (as compared to being entered in your code somewhere), I'm not sure why.

**Comment by mrmarkfrench** [comment]
What directory are you in when you are running `php composer.phar install` ? If you're not running it from the root of your project (that is, whatever directory `/vendor` is inside of, and where your `composer.json` file is located), try it from there and see if it makes any difference.

**Comment by mrmarkfrench** [comment]
This has now been resolved.
