### ISSUE TITLE
Receiving an error at BuyerAccount Creation

### ISSUE THREAD

**Issue by Zuhayer** [Armor-Payments/armor-payments-php#5]
I am following the example in example_goods_milestones_order.php to integrate the sdk in my app.

Framework:
Symfony version 2.3.42 - app/dev/debug

Code:
```
try
        {
            require_once($this->container->getParameter('kernel.root_dir') . '/../armor-payments-php-master/lib/ArmorPayments/ArmorPayments.php');

            $payoneerApiKey = $this->container->getParameter('payoneer_api_key');
            $payoneerApiSecret = $this->container->getParameter('paypal_client_secret');
            $client = new \ArmorPayments\Api($payoneerApiKey, $payoneerApiSecret, true);

            $unique = uniqid();

            $buyerAccount = $client->accounts()->create(array(
                'company'    => "DevClan{$unique}",
                'address'    => 'Near Expo Center',
                'city'       => 'Lahore',
                'country'    => 'pk',
                'zip'        => '54000',
                'user_name'  => "Farhan{$unique}",
                'user_email' => "zuhayer.tahir.devclan+{$unique}@gmail.com",
                'user_phone' => '+923224110667',
            ));
// error occurs here
            echo print_r($buyerAccount, true)."\n"; 
            $buyerUser = $client->accounts()->users($buyerAccount->account_id)->all();
            $buyerUser = $buyerUser[0];
            echo print_r($buyerUser, true)."\n";

            return new Response('end');
        } catch (\Exception $e){
            return new Response($e->getMessage());
        }

```
Error:

`stdClass Object ( [status] => error [errors] => stdClass Object ( [authentication] => Array ( [0] => Invalid request signature ) ) ) `

I am unable to find any reference for the correct values. 

Kindly guide me, what I am doing wrong.

**Comment by mrmarkfrench** [comment]
It looks like you're using a value called `payoneer_api_key`, but then another value called `paypal_client_secret`. Did you mean to load something like `payoneer_client_secret` instead?

If you're using a secret value that doesn't match your key, that would definitely lead to authentication errors.

**Comment by Zuhayer** [comment]
In my sandbox profile https://sandbox.armorpayments.com/accounts/.... it only mentions API Key. There is no api_secret value generated or mentioned.

![screenshot 5](https://cloud.githubusercontent.com/assets/5408155/24688680/f29abfd0-19da-11e7-8eb5-7c720ec8e213.png)

So as the example required an `api_secret` I used a long string value `paypal_client_secret` from my parameters.yml file. I forgot to change the variable name, but it is meant to be `payoneer_client_secret`:

```
// $api_key    = "ENTER_YOUR_API_KEY_HERE";
// $api_secret = "ENTER_YOUR_API_SECRET_HERE";


$client = new \ArmorPayments\Api($api_key, $api_secret, true);
```

Is the `$api_secret` also provided by Payoneer?

**Comment by Zuhayer** [comment]
@mrmarkfrench 
Currently i am getting this error:
```
{#633 ▼
  +"status": "error"
  +"errors": {#632 ▼
    +"authentication": array:1 [▼
      0 => "Invalid request signature"
    ]
  }
}
```

**Comment by mrmarkfrench** [comment]
The `api_secret` will never be displayed in the application. It was included in the email sent to you when your API key was first created, which would have been emailed to you directly. Check your email for this value.

**Comment by Zuhayer** [comment]
@mrmarkfrench Thank you for your help. I found the `api_secret` in the email that I received. The API is working fine now.

**Comment by mrmarkfrench** [comment]
Great! Glad to hear it's working for you.
