### ISSUE TITLE
How to refund

### ISSUE THREAD

**Issue by 7krasov** [Armor-Payments/armor-payments-php#7]
Hi, could you tell me how to refund an order particulary for 
'order_type'  => 3, // An escrow order for services
'milestones'  => [['name'] => 'name1', 'amount' => 'amount1'], ['name'] => 'name2', 'amount' => 'amount2']]

Initiator - partner

or at least whole order?

**Comment by mrmarkfrench** [comment]
If you cancel the order, all funds remaining in escrow will be returned to the buyer.
`POST /accounts/12345/orders/67890`
`{ action:"cancel", confirm:true }`

**Comment by mrmarkfrench** [comment]
Alternatively, for a milestone order, you can request that only part of the full milestone payment be released to the seller. In that case, the remainder will be refunded to the buyer.
`POST /accounts/12345/orders/67890`
`{ "action":"complete_service_partial", "confirm":true, "amount":1000.00, "message":"I quoted $1500, but we finished the job in less time than expected. The remaining $500 will be returned to you." }`

This will request a partial payout for the currently active milestone.
